### ISSUE TITLE
Add `elm-version` field to `elm-package.json`

### ISSUE THREAD

**Issue by DavidHarrison** [TheSeamau5/elm-random-extra#3]
Newer Elm package management requires and `elm-version` field in `elm-package.json` of the form `0.15.0 <= v < 0.16.0`.

Thanks,
David Harrison

**Comment by TheSeamau5** [comment]
Thanks. This is fixed with the new update. Will be live shortly

**Comment by DavidHarrison** [comment]
Thanks!

**Comment by TheSeamau5** [comment]
Btw, the new version has quite a big overhaul. There are many reasons for the overhaul: `Random.Extra` was too big to make any sense of. Lots of new functionality had to come in so I made things look more consistent.

I made sure to not break any code that I really didn't have to. But you can see more or less a summary of the changes here: https://github.com/TheSeamau5/elm-random-extra/pull/4

Hopefully, with the update, you can use elm-random-extra to generate all sorts of stuff (possibly entire applications).
